package kh.ppt.exception;

public class UserExceptionTest {
	public void method() throws UserException {
		throw new UserException("예외발생");
	}
}
